#pragma once

// Trace logging.
#define ENABLE_WORLD_LOG_TRACE false
#define ENABLE_REPLICATION_LOG_TRACE false
#define ENABLE_CONNECTION_CONTEXT_LOG_TRACE false
#define ENABLE_CONNECTION_BACKEND_LOG_TRACE false
